version: '3'
services: 
    db:
        image: postgres:12-alpine
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=changeme
            - POSTGRES_DB=databasename
    web:
        build:
            context: .
            dockerfile: Dockerfile.debug
        environment: 
            - DATABASE_USERNAME=postgres
            - DATABASE_PASSWORD=changeme
            - DATABASE_NAME=databasename
        ports:
            - "8080:8080"
        restart: always
        depends_on: 
            - db
volumes: 
    postgres_data:
