FROM debian:latest

LABEL Maintainer="David Rocca - The MITRE Corporation"

RUN apt-get update && apt-get install -y apache2 \
    libapache2-mod-wsgi \
    build-essential \
    python \
    python-dev \ 
    python-pip \
&& apt-get clean \
&& apt-get autoremove \
&& rm -rf /var/lib/apt/lists/*

VOLUME [ "/data" ]
WORKDIR /data

# Copy over Python Requirements
COPY ./requirements.txt /var/www/apache-flask/app/requirements.txt
RUN pip install -r /var/www/apache-flask/app/requirements.txt

# SSL Keys
#COPY ./<key-name>.key /etc/apache2/<key-name>.key
#COPY ./<cert-name>.crt /etc/apache2/<cert-name>.key

COPY ./apache-flask.conf /etc/apache2/sites-available/apache-flask.conf
RUN a2ensite apache-flask
RUN a2enmod headers
## Run the SSL Mod
RUN a2enmod ssl

COPY ./apache-flask.wsgi /var/www/apache-flask/apache-flask.wsgi
COPY ./run.py /var/www/apache-flask/run.py
COPY ./app /var/www/apache-flask/app/
COPY ./config.py /var/www/apache-flask/
COPY ./manage.py /var/www/apache-flask/

#Disable the default apache site
RUN a2dissite 000-default.conf
RUN a2ensite apache-flask.conf

# If HTTP:
EXPOSE 80
# IF HTTPS:
#EXPOSE 443

WORKDIR /var/www/apache-flask

# Copy over the entry script
COPY ./startup-release.sh /root/startup.sh
CMD /root/startup.sh